version: '2'
services:
    mysecondapp-app:
        image: mysecondapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mysecondapp-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=mySecondApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mysecondapp-mongodb:
        extends:
            file: mongodb.yml
            service: mysecondapp-mongodb
